name: .NET - Add latest build to Github Release

on:
  release:
    types: [created]
    name: Release  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build AzureCommunicationServicesGetStartedApis.csproj
    - name: Publish
      run: dotnet publish AzureCommunicationServicesGetStartedApis.csproj
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "local.settings.template.json"
        target: " ./bin/Debug/netcoreapp3.1/publish/local.settings.json"
    - name: Create Release
      shell: bash
      run: |
        release_name=Group-Calling
        unset CI
        7z a -tzip -r "AzureCommunicationServicesGetStartedApis.zip" ./bin/Debug/netcoreapp3.1/publish/*
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: "AzureCommunicationServicesGetStartedApis.zip"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
